### ISSUE TITLE
Try out smarty filters instead of own theme

### ISSUE THREAD

**Issue by nuest** [TIBHannover/ojsGeo#70]
Instead of using an own theme for #69, consider just doing a string replacement with a smarty filter, see https://github.com/ajnyga/forthcoming/blob/master/ForthcomingPlugin.inc.php#L116 (and other functions in that file).

**Comment by nuest** [comment]
See also docs at https://docs.pkp.sfu.ca/pkp-theming-guide/en/html-smarty

**Comment by GaziYucel** [comment]
// register method
HookRegistry::register('TemplateManager::display', array($this, 'templateDisplayHandler'));

// handler
function templateDisplayHandler($hookName, $args): bool
{
	$templateMgr = &$args[0];
	$template = &$args[1];

	switch ($template) {
		case 'frontend/pages/article.tpl':
			$templateMgr->registerFilter("output", array($this, 'templateDisplayHandlerArticle'));
			break;
		default:
			break;
	}

	return false;
}

// article part for handler
function templateDisplayHandlerArticle($output, $templateMgr): string
{
	$output .= "<span style='background-color: red;'>templateDisplayHandlerArticle</span>";
	$templateMgr->unregisterFilter('output', array($this, 'templateDisplayHandlerArticle'));
	return $output;
}

**Comment by nuest** [comment]
For the default theme, a possible regex-Startpoint is the String `</div><!-- .sections -->`, see https://github.com/ifgi/optimetaGeoTheme/blob/308aef63ece60b0b88df1665b72e436c0cd571b4/templates/frontend/objects/issue_toc.tpl#L139

```php
{call_hook name="Templates::Issue::TOC::Main"}
	</div><!-- .sections -->
```

**Comment by nuest** [comment]
This is not a sustainable solution because vue.js will also be used in the frontend more and more.
